<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57e51ea871f79-2',
	'title' => 'Page à bandeau',
	'fields' => array (
		array (
			'key' => 'field_57e51ea874ee7',
			'label' => 'Sous-titre de la page',
			'name' => 'bandeau-soustitre',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57e51ea874fab',
			'label' => 'Image de fond du bandeau',
			'name' => 'bandeau-image',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array (
		0 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57e50d46e11d2',
	'title' => 'Page à composants',
	'fields' => array (
		array (
			'key' => 'field_57e5133fa8356',
			'label' => 'Composants',
			'name' => 'composants',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Ajouter un composant',
			'min' => 1,
			'max' => '',
			'layouts' => array (
				array (
					'key' => '57e50d66aeb0c',
					'name' => 'intertitre',
					'label' => 'Intertitre',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_57e5133fa8357',
							'label' => 'Titre',
							'name' => 'titre',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_57e5133fa8358',
							'label' => 'Ancre',
							'name' => 'ancre',
							'type' => 'text',
							'instructions' => 'Ne pas utiliser de caractères accentués ou de ponctuation. Remplacer les espaces par des tirets (-).',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '#',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_57e5133fa8359',
							'label' => 'Niveau de titre',
							'name' => 'niveau',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 2,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 2,
							'max' => 4,
							'step' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57e50e1615b88',
					'name' => 'texte',
					'label' => 'Texte',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57e5133fa835a',
							'label' => 'Texte',
							'name' => 'texte',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57e50e7015b8b',
					'name' => 'liens',
					'label' => 'Liens',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57e51340a835b',
							'label' => 'Titre',
							'name' => 'titre',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Liens',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_57e51340a835c',
							'label' => 'Lien',
							'name' => 'lien',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Ajouter un lien',
							'sub_fields' => array (
								array (
									'key' => 'field_57e51340a835d',
									'label' => 'Intitulé',
									'name' => 'intitule',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_57e51340a835e',
									'label' => 'Lien interne',
									'name' => 'lien_interne',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 1,
									'allow_archives' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_57e51340a835f',
									'label' => 'URL externe',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57e515ef99173',
					'name' => 'outils',
					'label' => 'Liste d\'outils',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57e516b899179',
							'label' => 'Outils',
							'name' => 'outils',
							'type' => 'repeater',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_57e516db9917a',
							'min' => '',
							'max' => '',
							'layout' => '',
							'button_label' => 'Ajouter un outil',
							'sub_fields' => array (
								array (
									'key' => 'field_57e516db9917a',
									'label' => 'Titre',
									'name' => 'titre',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_57e516e39917b',
									'label' => 'Description',
									'name' => 'description',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'visual',
									'toolbar' => 'basic',
									'media_upload' => 0,
								),
								array (
									'key' => 'field_57e5170d9917c',
									'label' => 'Icône',
									'name' => 'icone',
									'type' => 'select',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'flore' => 'flore',
										'carnet' => 'carnet',
										'base' => 'base',
										'mobile' => 'mobile',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array (
									'key' => 'field_57e517329917d',
									'label' => 'Lien',
									'name' => 'lien',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'allow_archives' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_57e517639917e',
									'label' => 'Intitulé du lien',
									'name' => 'intitule_du_lien',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 'Accéder à cet outil',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57e998678f0d7',
					'name' => 'bouton',
					'label' => 'Bouton',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_57e9986d8f0d8',
							'label' => 'Intitulé',
							'name' => 'intitule',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_57e9987b8f0d9',
							'label' => 'Lien interne',
							'name' => 'lien',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

endif;
