<?php

acf_add_local_field_group(array (
	'key' => 'group_58034d2dc9585',
	'title' => 'Offre de stage',
	'fields' => array (
		array (
			'key' => 'field_58034d2ddf6a0',
			'label' => 'Chapo',
			'name' => 'chapo',
			'type' => 'text',
			'instructions' => '[structure] propose un stage de [durée]',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58034d2ddf73d',
			'label' => 'Contexte',
			'name' => 'contexte',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034d2ddf7d6',
			'label' => 'Missions',
			'name' => 'missions',
			'type' => 'textarea',
			'instructions' => 'Noter les missions confiées au stagiaire',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034d2ddf86f',
			'label' => 'Profil recherché',
			'name' => 'profil_recherche',
			'type' => 'textarea',
			'instructions' => 'Noter le profil recherché',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034d2ddf908',
			'label' => 'Conditions',
			'name' => 'conditions',
			'type' => 'textarea',
			'instructions' => 'Noter les conditions du stage',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034d2ddf9a2',
			'label' => 'Modalités de candidature',
			'name' => 'modalites_de_candidature',
			'type' => 'textarea',
			'instructions' => 'Candidatures (CV & L.M) à envoyer avant le [date limite] à [contact]',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034d2ddfa5c',
			'label' => 'Renseignements / contacts supplémentaires',
			'name' => 'renseignements_contacts_supplementaires',
			'type' => 'textarea',
			'instructions' => 'Noter les contacts pour demande de renseignements',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array (
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:stages',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));
