<?php

acf_add_local_field_group(array (
	'key' => 'group_58034a4d87ab4',
	'title' => 'Offre d\'emploi',
	'fields' => array (
		array (
			'key' => 'field_58034a58a9784',
			'label' => 'Chapo',
			'name' => 'chapo',
			'type' => 'text',
			'instructions' => '[structure] recherche un.e [titre de poste] en [type du contrat/durée]',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58034aa1ef07d',
			'label' => 'Contexte',
			'name' => 'contexte',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034ab6ef07e',
			'label' => 'Missions',
			'name' => 'missions',
			'type' => 'textarea',
			'instructions' => 'Noter les missions confiées au poste',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034acaef07f',
			'label' => 'Profil recherché',
			'name' => 'profil_recherche',
			'type' => 'textarea',
			'instructions' => 'Noter le profil recherché',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034adeef080',
			'label' => 'Poste',
			'name' => 'poste',
			'type' => 'textarea',
			'instructions' => 'Noter les conditions du recrutement',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034b05ef081',
			'label' => 'Modalités de candidature',
			'name' => 'modalites_de_candidature',
			'type' => 'textarea',
			'instructions' => 'Candidatures (CV & L.M) à envoyer avant le [date limite] à [contact]',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58034b20ef082',
			'label' => 'Renseignements / contacts supplémentaires',
			'name' => 'renseignements_contacts_supplementaires',
			'type' => 'textarea',
			'instructions' => 'Noter les contacts pour demande de renseignements',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array (
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:cdd-cdi',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));
