<?php

acf_add_local_field_group(array (
	'key' => 'group_580409b4f02aa',
	'title' => 'Moyens de participer',
	'fields' => array (
		array (
			'key' => 'field_580409bc2c86d',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_580409d72c86e',
			'label' => 'Description courte',
			'name' => 'description_courte',
			'type' => 'textarea',
			'instructions' => 'Décrire en une phrase en quoi cela consiste.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_580409f32c86f',
			'label' => 'Intitulé du bouton',
			'name' => 'intitule_bouton',
			'type' => 'text',
			'instructions' => 'Intitulé qui sera affiché sur le bouton permettant de passer à l\'action.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Commencer',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58040a202c870',
			'label' => 'Destination',
			'name' => 'destination',
			'type' => 'page_link',
			'instructions' => 'Au clic sur ce moyen de participer, l\'utilisateur sera redirigé sur cette page.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
				1 => 'page',
				2 => 'tb_thematique',
				3 => 'tb_outil',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tb_participer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
